/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avalokita_jlcall_JLcall */

#ifndef _Included_com_avalokita_jlcall_JLcall
#define _Included_com_avalokita_jlcall_JLcall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_avalokita_jlcall_JLcall
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_avalokita_jlcall_JLcall_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
